### ISSUE TITLE
GUI For Creating XLSForms within Cadasta

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#10]
## Skills Needed
- JavaScript
- Python/Django
## First Task

Find a bug and attempt to fix it. You can find possible bugs [here](https://github.com/Cadasta/cadasta-platform/issues) or you can look for them yourself. 
## Project Description

Cadasta uses the [XLSForm](http://xlsform.org/) standard to both define the data schema of a project and to create forms for data entry. The XLSForm standard can be a bit complicated for some people to use so we'd like to provide a GUI within Cadasta to make that easier. There is [existing software](https://opendatakit.org/use/xlsform/) that already provides GUI to do this you might look at for inspiration. 
## User Stories
- As a user I want to be able to view an XLSForm through a web GUI
- As a user I want to be able to create a new XLSForm through a web GUI
- As a user I want to be able to modify an existing XLSForm through a web GUI
- As a user I want to be able to delete existing fields from the XLSForm
- As a user I want to be able to add new fields to an existing XLSForm
- As a user I want to be able to add new drop down options for select types
- As a user I want to be able to remove drop down options for existing select types
### Existing Form
1. User uploads form
2. System parsing form
3. If required attributes are missing system states "The required attributes for a Cadasta Project are missing, would you like to add them now?"
4. User is then shown the form in the browser
5. User may then add and remove attributes
6. If user tries to remove a required attribute an error is shown ("That attribute is required for a Cadasta Project")
### Starting with a [Basic Cadasta](https://docs.google.com/spreadsheets/d/1gB7lcz4Dr6aqdW_Oesuum2pbI8lzs6EYTLpVZGQMhcQ/edit#gid=2006567796) Form
1. User select they would like to start with the basic form
2. User is shown basic form
3. User may then add attributes
4. If user tries to remove a required attribute an error is shown ("That attribute is required for a Cadasta Project")
## Ancillary Information

The required attributes for a Cadasta project are:
- party_type
- party_name
- location_geometry
- location_type
- tenure_type

Possible Mentor: @bjohare

**Comment by kavindya89** [comment]
@wonderchook Thanks for detailed project description. I have following questions in my mind.

So the basic idea is to provide a web interface for create, modify XSLForms through Web GUI right?
We need to have a separate view which enables user to upload XSLForm or create brand new XSLForm. This is to hide the complexity of creating complex XSLForms by using XSL sheets. So with web interface, user will present rich UI where they add and drops UI components to create XSLForm. Please let me know my idea is correct.

**Comment by wonderchook** [comment]
Not quite, but you are mostly right. We want to get away from using
XLSForms for modification and creation of project schemas in Cadasta. We
will still support creation of project schema with XLSForms upon creation
for a while though.

So the idea is a GUI for users to create the project schema.

**Comment by manoramahp** [comment]
@wonderchook As I got clarified from @bjohare, this project is about creating a UI editor to generate XForms instead of generating them from XLSForms. So if I'm not mistaken the intention of this project is to move away from XLSForms and directly generate XForms from the UI as in ODK build.

Further, since the XLSForm format is bit complicated to some users, they will find this UI much user-friendly because when they already have an XLSForm which they need to edit, they can simply upload it through this wizard and do the necessary editing (add/edit/delete questions) and convert it to an XForm.

To make this feature much user-friendly, I propose additionally we should have a questionnaire preview UI to see how the questionnaire a user is designing will look like at the end.

**Comment by karenc** [comment]
## Current Behavior

From what I understand, users can upload an excel file (using the XLSForm structure) on a project details page to create a questionnaire.

I had a look at what cadasta is currently doing with the uploaded excel / xls file and it seems to:

1. store the xls file,
2. parse the file to json using `pyxform.xls2json.parse_file_to_json`,
3. generate an XForm file using `pyxform.builder.create_survey_element_from_dict` and store it,
4. create `Questionnaire`, `QuestionGroup`, `Question`, `QuestionOption` models.

At first I wasn't sure how the questionnaires are used as they are not displayed on the site.  There are only APIs:

 - `/collect/formList/`: for returning the list of questionnaires that the user has access to,
 - `/collect/submission`: for submission of completed questionnaires (I think).

After playing around with the "ODK Collect" Android app, I think I start to understand how the questionnaires are used.  I configured the ODK Aggregate settings to use my dev server.  The app found the questionnaires on my dev server and I was able to complete the questionnaire on my phone.  The submission didn't work but I think I get the idea.

## Project Plan

The way I would approach this project is:

1. Create a tab (or a menu item) for viewing the questionnaire (similar to how ODK Collect displays it) on the project page.
2. Move the questionnaire upload field from the project details page to the questionnaire page.
3. Design and implement a GUI for CRUDing `Questionnaire`, `QuestionGroup`, `Question`, `QuestionOption` models.
4. Write a serializer to serialize `Questionnaire` to XForm.

---

@wonderchook How does this look to you?

**Comment by oliverroick** [comment]
@karenc I'm currently working on extending the API so that Questionnaires can be updated via the API. This includes some changes how XLSForm uploads will be handled in the future:

1. Store the XLS file
2. parse the file to JSON using `pyxform.xls2json.parse_file_to_json`
3. From the JSON create `Questionnaire`, `QuestionGroup`, `Question`, `QuestionOption` instances

XForms will be created from `Questionnaire`, `QuestionGroup`, `Question` and `QuestionOption` and made available via an API endpoint. So writing a serializer to serialize `Questionnaire` to XForm will be something you won't have to worry about, this will be in place soon.

**Comment by karenc** [comment]
@oliverroick That's great news! Thanks for the update! :tada:
