### ISSUE TITLE
Field Papers UI improvements

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#2]
**Note: Currently Cadasta has many more for Outreachy applicants than we can accept. If you have not already made an initial contribution to a project it is best you look for another organization within Outreachy that doesn't have as many applicants.**

Field Papers is a web application that allows someone to print maps, annotate those maps and then reupload them. It is a tool used around the world for community mapping. One of the tasks planned for the current Cadasta work on [Field Papers](http://fieldpapers.org/) is to extract the Javascript UI layer used in Field Papers into a seperate component that can be used in other mapping applications (obviously including Cadasta!). The UI as it stands is quite sparse, and there are a few things that could be done to improve it, some of which might be quite fun:

 * *More flexible atlas region definition* At the moment, atlases are defined over a rectangular grid of pages, but there are use cases for more interesting arrangements, including rotating the grid (so that page boundaries can be made parallel to roads and other linear features) and creating pages along a linear or polyline track (for surveying roads and other linear features or for surveying along GPS/KML tracks). [Issues: [#179](https://github.com/fieldpapers/fieldpapers/issues/179), [#153](https://github.com/fieldpapers/fieldpapers/issues/153)]

 * *Bug fixes* There are quite a few outstanding issues on the UI side in Field Papers, of varying levels of annoyance. Dealing with some of these might be a good way for an intern to get started. [Issues: [#146](https://github.com/fieldpapers/fieldpapers/issues/146), [#145](https://github.com/fieldpapers/fieldpapers/issues/145), [#142](https://github.com/fieldpapers/fieldpapers/issues/142), others?]

 * *UI styling* This is potentially the most fun part. The Field Papers UI is pretty simple, and there are a number of changes I could imagine making to make it a bit more configurable for embedding in web apps other than the main Field Papers site. All the obvious things: making colours and the sub-components of the UI (buttons, handles, etc.) configurable. I'm sure Chandra and the new design person would have suggestions of how best to do this, and it would also be a good way for the intern to contribute something visible to the main Cadasta platform, since they could be responsible for the styling of the Field Papers UI on the main Cadasta site.

I think this would work best for an internship if the intern spent a week or two on code familiarisation, getting a development environment set up and fixing a couple of small UI bugs from the list above -- that way they can generate PR-able changes quite quickly. Once they're a bit familiar with the code, they could then decide which of the two bigger parcels of work they'd like to address first. My inclination would be to suggest UI styling first, since again it should give quick visible results, and it will also lead to a deeper understanding of what's going on in the code, which will be needed for modifying the atlas region definition.

**Skills required:** just front-end Javascript!

**Suggested initial task:**  have a go at fixing issue [#142](https://github.com/fieldpapers/fieldpapers/issues/142) -- this will involve looking a bit at the model of interaction between the FP UI and the Leaflet map that it's embedded in, but shouldn't involve too much new coding.  (You'll also make a lot of people happy if you fix it!)

**Possible Mentors:** @ian-ross, @clash99

**Comment by ian-ross** [comment]
Here are some brief notes to help getting started with looking at the suggested initial task.  This is fixing [issue #142](https://github.com/fieldpapers/fieldpapers/issues/142) in the Field Papers web app, which is a problem in the user interface used for setting up atlas pages.

### Getting started

The absolute first thing to do is to read the [description of the issue](https://github.com/fieldpapers/fieldpapers/issues/142) (which is quite clear and has screenshots to illustrate the problem) and then to go to http://fieldpapers.org and try creating some atlases yourself to get a feeling for how the interaction model of the atlas page selection UI works (and how it's broken!).

After you've read the rest of this, you might then want to come back and experiment again, trying to work out what's going on in the page composer Javascript code as you perform different actions in the UI.

### Development environment

In order to test changes you make to the Field Papers code, you don't need to run the whole Field Papers application stack (which includes the main Rails web app, a task manager for image processing, a tile server and a database instance).  However, you do need:

1. A MySQL database.
2. An installation of a recent version of Ruby (2.2.2 or later, I think).
3. The Ruby support tools (in particular, [Bundler](http://bundler.io/)).

If you have the prerequisites installed, getting the Field Papers web app set up shouldn't require much more than forking the `fieldpapers/fp-web` repository on GitHub and doing (NOTE: don't just cut and paste this -- you need to substitute vaues for the things in `<angle brackets>`):

```
git clone https://github.com/<my-user-name>/fp-web.git
cd fp-web
bundle install
export DATABASE_URL=mysql2://<db-user>:<db-password>@localhost/fieldpapers_development
export TEST_DATABASE_URL=mysql2://<db-user>:<db-password>@localhost/fieldpapers_test
rake db:create
rake db:schema:load
rails server
```

Then you can go to http://localhost:3000/ in your browser and you should see the Field Papers front page.

How easily or not this all works depends on what platform you're working on (these instructions assume Linux and bash).  If you have trouble with getting set up, either send a message to the Google Group or post a comment below and I'll try to help.

### Where to look

The part of the atlas setup pipeline we're interested in here is rendered from the [app/views/compose/select.html.erb](https://github.com/fieldpapers/fp-web/blob/master/app/views/compose/select.html.erb) view template in the Rails app.  This has a `DIV` called `map` which  is a placeholder for the [Leaflet](http://leafletjs.com) slippy map, and which gets set up by a Javascript call to a function called `FP.map.compose.select`, which is defined in [app/assets/javascripts/fp/map/compose.select.js](https://github.com/fieldpapers/fp-web/blob/master/app/assets/javascripts/fp/map/compose.select.js).

There are two things you need to know here:

1. All the references to `L.something` in these Javascript files refer to things in the Leaflet namespace.  If you're not familiar with Leaflet, you should take a look at the documentation on the [website](http://leafletjs.com).  Leaflet is a lightweight Javascript slippy map library and it doesn't take too long to learn.

2. The user interface for selecting the atlas pages is set up [here](https://github.com/fieldpapers/fp-web/blob/master/app/assets/javascripts/fp/map/compose.select.js#L50-L51).  The `L.pageComposer` thing referred to there is defined in [app/assets/javascripts/leaflet/leaflet-page-composer.js](https://github.com/fieldpapers/fp-web/blob/master/app/assets/javascripts/leaflet/leaflet-page-composer.js).  This is the key thing you need to be looking at, since it's the code that defines the interaction model of the atlas page selection UI.

**Comment by smarshy** [comment]
Hi ,i went through the "getting started" notes .Is it necessary to use a recent version of ruby?As it so happens,I am using ubuntu 14.04 and the default version is 1.9.3.I did search for alternatives but also noticed issues with newer versions and couldn't find a suitable installer

**Comment by ian-ross** [comment]
@smarshy I don't know for sure what versions of Rails work with what versions of Ruby, but my guess would be that 1.9.3 might not work (major version number change).  What I do is use `rbenv` to manage Ruby versions.  That way you can work with whatever version you like, independent of what the OS package manager has available.

To set up `rbenv` (and the `ruby-build` utility that goes with it), do this:

```
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
```

then add this to the bottom of your `~/.bashrc`:

```
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
eval "$(rbenv init -)";
```

Log out, log back in again, then you can type `rbenv install 2.2.3` and hopefully after a few minutes, `ruby --version` will show that you have version 2.2.3 set up.

(Links to `rbenv`: https://github.com/sstephenson/rbenv and `ruby-build`: https://github.com/sstephenson/ruby-build)

**Comment by saijahnavi1537** [comment]
When I try to run rake db:create I am getting error. Can some one help me.![error](https://cloud.githubusercontent.com/assets/10941710/10218099/f0a853c2-6851-11e5-8775-43951d9e466f.png)

**Comment by ian-ross** [comment]
@saijahnavi1537 OK, this isn't something you could be expected to figure out.  What's happening is that the Rails web app uses some packages that call external Javascript programs to do some processing (looks like it's a Javascript code compactor/uglifier).  That means that it needs access to a server-side Javascript runtime, which you don't have.  I don't see this problem on my development machine because I have Node.js installed and the Ruby `execjs` gem just picks that up and uses it as the Javascript runtime.

There are two possible fixes.  Either you can install Node.js, which I don't really recommend if you're not otherwise using it, or you can use something called [therubyracer](https://rubygems.org/gems/therubyracer/versions/0.12.2), which is a gem that uses the V8 Javascript engine to provide a Javascript runtime directly within Ruby.  You can install this by adding the following line to your `Gemfile`:

```
gem 'therubyracer', '~> 0.12.2'
```

and doing `bundle install` again to get the thing installed.  **Note that this will probably NOT work on Windows, because you need to do some extra stuff to get the V8 engine installed there.**

**Comment by saijahnavi1537** [comment]
@ian-ross  Yeah it worked. after I installed node.js

**Comment by TwinkleChawla** [comment]
When I ran 'rake db:create' and 'rake db:schema:load' this happened:
![screenshot from 2015-10-07 00 56 51](https://cloud.githubusercontent.com/assets/12040806/10319922/52a1adf4-6c8e-11e5-9af2-de278289594b.png)

**Comment by ian-ross** [comment]
@TwinkleChawla  Take a look at the [comment above](https://github.com/Cadasta/cadasta-project-ideas/issues/2#issuecomment-144526182) about Ruby versions.  The error message you're getting is telling you that the Ruby version you have installed (1.9.3, which I think is currently the standard for Ubuntu 14.04) doesn't match with the version that's declared in the `Gemfile` (which specifies a fixed Ruby version to avoid interpreter incompatibilities between different versions).  The best thing to do is to use `rbenv` to manage your Ruby versions, as described in the comment I linked to.

**Comment by TwinkleChawla** [comment]
@ian-ross: I did ruby configurations for 2.2.3 setup but still 'rake db:create' is showing:
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

**Comment by ian-ross** [comment]
@TwinkleChawla  Where are you trying to run Rake?  You should be in the top-level `fp-web` directory.  There's definitely a Rakefile there!  And did you do a `bundle install` in the `fp-web` directory again after you set up the new Ruby version?

**Comment by TwinkleChawla** [comment]
After doing 'bundle install' , it again shows:
Your Ruby version is 1.9.3, but your Gemfile specified 2.2.2

**Comment by ian-ross** [comment]
@TwinkleChawla  What version does `ruby --version` show?  And which Ruby executable is actually being used -- what does `which ruby` show?  It sounds like the `rbenv` setup stuff you should have put into your `.bashrc` isn't working right.

**Comment by TwinkleChawla** [comment]
Its again 1.9.3 version, but I just copied down the above written stuff into .bashrc!

**Comment by ian-ross** [comment]
What does `which ruby` show?  And is `~/.rbenv/shims` in your PATH?  (If not, that shows that the `rbenv` stuff hasn't run when you opened your shell.)

**Comment by TwinkleChawla** [comment]
@ian-ross 'rbenv' is running..
![screenshot from 2015-10-07 02 00 07](https://cloud.githubusercontent.com/assets/12040806/10321590/27f7c15c-6c97-11e5-8123-66e66c4c1a8d.png)

**Comment by ian-ross** [comment]
@TwinkleChawla  I don't think it's set up right.  The fact that `which ruby` says `/usr/bin/ruby` shows that the `rbenv` path isn't set up correctly.  Here's what I see:

```
[seneca:~] $ which ruby
/home/iross/.rbenv/shims/ruby
[seneca:~] $ echo $PATH
/home/iross/.rbenv/shims:lots-more-stuff-you-don't-need-to-see
```

What happens if you just cut and paste the `rbenv` initialisation code into your terminal window:

```
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
eval "$(rbenv init -)"
```

**Comment by smarshy** [comment]
@TwinkleChawla Hi! I actually ran into each and every error you have mentioned here.
The first comment would help you in setting up rbenv. If you still have problems you could refer to the tutorial below.It is actually pretty much the same thing and it worked for me.

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-14-04

To resolve the 'No Rakefile found' error,I needed to switch to the main fp-web directory
For the 'your Gemfile specified 2.2.2' error, I think you need to have ruby 2.2.2 installed.I had installed 2.2.3.It even showed up in the ruby version but I still ran into this error.I then installed version 2.2.2 and then it turned out to be fine.Hope this helps.

**Comment by ian-ross** [comment]
@smarshy  Thanks for the link to that tutorial.  I think that will be useful for a lot of people.

**Comment by TwinkleChawla** [comment]
@smarshy Thanks for the link.. Now I am done with it!

**Comment by shamika89** [comment]
@ian-ross
I am trying to set up the project in windows environment. When I executed rake db:create command I encountered the following error.

E:\Casendra\fp-web>rake db:create
rake aborted!
LoadError: cannot load such file -- nokogiri/nokogiri                         

But when I executed 'bundle show nokogiri' it showed that 'nokogiri' was existing.

**Comment by ian-ross** [comment]
@shamika89  I think you'll have a much better time using a Linux VM for this.  The `nokogiri` gem uses native extensions and so getting it working on Windows requires some extra steps.  The Field Papers server runs on Linux servers.  I don't know if anyone has ever got the code working on Windows, but it will be *much* easier if you use a Linux VM.  Just install VirtualBox and set up an Ubuntu 14.04 VM.  (If you're not used to using VMs, it's a very useful thing to learn about.)

**Comment by shamika89** [comment]
@ian-ross Thank you for the advise. I'll try to use Ubuntu.

**Comment by wonderchook** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nSfXH2aN&#x2F;1-field-papers"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Field Papers</a>

**Comment by khushbuparakh** [comment]
Hi! I am khushbu an Outreachy 2016 applicant. I am quite familiar with Leaflet and ROR and I have set the developer environment as per instruction given by @ian-ross. Looking forward to solve my first issue.
Please help me guiding to it and I would also like to know whether an IRC channel is there for "Cadasta"

**Comment by ian-ross** [comment]
@khushbuparakh This project is closed.  Only open issues labelled "Outreachy" are going to be offered as Outreachy projects in this round: https://github.com/Cadasta/cadasta-project-ideas/issues?q=is%3Aissue+is%3Aopen+label%3AOutreachy

**Comment by khushbuparakh** [comment]
ok thanks @ian-ross . I will look at  the issues.
