### ISSUE TITLE
Land and Resource Rights Community Research and Segment Analysis

### ISSUE THREAD

**Issue by TheaGlitter** [Cadasta/cadasta-project-ideas#9]
# This project is closed to new applicants, we already have many people interested. Please either look at another project or organization.

The Cadasta Platform is a relatively new open-source project working to build a fit-for-purpose land and resource rights management system. When deployed alongside equitable and inclusive programs, this technology has the power to democratize the documentation and safe storage of land and resource rights in places where they do not exist today. Over the last year our technology team got software development started and we built the foundation of a vibrant and diverse community. We had a great experience with Outreachy in the past and are excited to extend some non/less technical internship opportunities to students this semester.

A key part of the success our organizational mission is a deep understanding of the key stakeholders and their role in the land and resource rights sector. Cadasta Foundation is offering a non-technical internship for students interested in getting hands on experience doing community research and network mapping. This is a fantastic opportunity for students who are interested in learning the processes and practices that go into creating a sustainable, inclusive community of open source technology creators and consumers.

Tasks for this project:

- Research and document select segments of the land and resource rights ecosystem. Who are the key stakeholders? What are they doing? Where are they working? 

- Assist Cadasta staff in documenting and visualizing the network of actors we will be engaging with as we work to spread the use of our Platform and Programs.

- Develop questions Cadasta Foundation can use during phone or email interviews with key stakeholders and assist Cadasta staff during phone or email interviews.

- Propose ways in which Cadasta might engage with certain stakeholders in order to expand our community.

Potential Mentors: @fhpichel  @theaglitter

Initial Task for Application: As a first task, please propose a list of 10 questions you would ask a land and resource rights expert in order to answer these two questions.
1: What is the biggest technology or workflow barrier they encounter during their normal activities.
2. What is their strategic role in the land and resource rights ecosystem.

**Comment by essymo** [comment]
Hi @fhpichel @TheaGlitter @wonderchook , My name is Esther and I am interested in this project.

**Comment by wonderchook** [comment]
Hi @essymo great, let us know if you have any questions as you get started.

**Comment by MMBazel** [comment]
Hi @wonderchook @TheaGlitter, I'm interested in this project as well. My name is Mikiko and I'm currently a GIS student with a background as an analyst and education in public health. Looking forward to collaborating with you on this project.

**Comment by TheaGlitter** [comment]
Welcome @MMBazel Please let me know if you have any questions. Thank you for your interest in this internship.

**Comment by ankita0000** [comment]
Hi @wonderchook @TheaGlitter @fhpichel 
am ankita and am interested in
internship and looking forward to be associated
with cadasta .I am a student pursing my
engineering.

**Comment by wonderchook** [comment]
Hi @ankita0000 thanks for your interest. Please let us know if you have questions.

**Comment by essymo** [comment]
@wonderchook @TheaGlitter https://github.com/essymo/cadasta/wiki Here is a sample of the initial Task for application question,Kindly look at it and tell me if I am on the right track.Thank you

**Comment by MMBazel** [comment]
Hi @TheaGlitter @wonderchook, 
Quick question on how you would like the drafts to be posted/delivered? 

Should we link here to a personal github wiki page, open an issue in a personal repository under our account? I've attached a link below but can do something different. 

[Initial list of questions]https://github.com/MMBazel/Cadasta/wiki/Land-and-Resource-Rights-Expert-Interview-(10-Questions)) 

A couple points: 
I feel that while they're a good first pass, they're not as specific or detailed as they could be. 

The overall process I pictured for the project (rather than just the task itself) is [illustrated here.](https://github.com/MMBazel/Cadasta/wiki/Segment-Analysis-and-Persona-Building-Process) 

It seems that right now we're interested in how individuals relate to their work (the day-to-day) as well as how they relate to the sector. Would it be useful to also prepare questions that cover in more depth how individuals relate to other individuals (in their current organization) and how they relate to individuals in other organizations?

**Comment by sunita00** [comment]
hello @TheaGlitter @wonderchook  i am sunita  from India and am working professional ,i want to get exposure to leverage my technical skills under cadasta. i am interested in this internship.

**Comment by wonderchook** [comment]
Hi @MMBazel as a link to your personal wiki page is fine. The one item I think is missing in your questions is more generic questions that get at our questions about technology. Can you think of ways to bring out what tools they use everyday in a different way. Maybe for example someone extensively uses WhatsApp to communicate with their colleagues and even assign tasks, but it doesn't occur to them that we might want to know that. They may only think of tools they directly use to collect data.

**Comment by wonderchook** [comment]
hi @sunita00 please let us know if you have any questions.

**Comment by MMBazel** [comment]
Hi @wonderchook, thanks for the feedback! 

I see your point and this is something I've run across to in leading db/crm implementations in that people will often take some aspects of their technological stack and workflows for granted. Still mulling over how to dig deeper. Thanks again for the feedback! :)

**Comment by MMBazel** [comment]
Hi @wonderchook @TheaGlitter, I've updated my interview questions page to include the following questions for determining tech usage:

  

- What kind of social media and mobile technology do you use during your day? What are the four main uses of mobile technology being applied in your daily activities?

- What are the different ways you document, visually and textually, rights issues you encounter while working?

- What are the steps and tools used while collaborating with colleagues (especially with remote colleagues)?

- When urgent situations occur, what kind of communication devices and tools do you use in order to seek guidance or help?

- Can you describe an instance (or many instances) where you didn't have access to these tools (and it impacted the outcome of a scenario)?

- If you could have access to a technology that existed right now, what would it be? (A variant could also be: What cool technology caught your eye recently?)

**Comment by MMBazel** [comment]
Hi @wonderchook @TheaGlitter, I've updated my [interview questions page](https://github.com/MMBazel/Cadasta/wiki/Land-and-Resource-Rights-Expert-Interview-(10-Questions)) to include the following questions for determining tech usage:

What kind of social media and mobile technology do you use during your day? What are the four main uses of mobile technology being applied in your daily activities?

What are the different ways you document, visually and textually, rights issues you encounter while working?

What are the steps and tools used while collaborating with colleagues (especially with remote colleagues)?

When urgent situations occur, what kind of communication devices and tools do you use in order to seek guidance or help?

Can you describe an instance (or many instances) where you didn't have access to these tools (and it impacted the outcome of a scenario)?

If you could have access to a technology that existed right now, what would it be? (A variant could also be: What cool technology caught your eye recently?)

Other sections remain the same. Happy to make any changes as needed!

**Comment by TheaGlitter** [comment]
Hi @MMBazel Thanks for the questions. I really like the narrative tone of the questions!

**Comment by Anagha1** [comment]
Hello all, 
I am Anagha Mohite from India and am working in eletronics. I got to know about this program very late,  so i am style working on the task to Be done, by sending this mail, I want to convey you that i am interested in participating this campaign.

**Comment by SonaliAg** [comment]
Hi @wonderchook @TheaGlitter @fhpichel 
I am Sonali Agrawal and I am interested in this project . I am a engineering student and interested in GIS.  [Here](https://github.com/SonaliAg/Cadasta/wiki/Land-and-Resource-Rights-Community-Research-and-Segment-Analysis---Initial-Task) is my initial task for this project. Waiting for the comments.

**Comment by deeptireddy** [comment]
[cadasta.docx](https://github.com/Cadasta/cadasta-project-ideas/files/181433/cadasta.docx)

Hi @wonderchook @TheaGlitter @fhpichel 
I am Deepti Reddy and I am interested in this project. The initial task is attached. 
It would be really nice to get some feedback. Thank You.

**Comment by Anagha1** [comment]
hi @TheaGlitter @wonderchook 
i have completed the initial task and the initial task is attached .

- [ ] 
[cadasta task 1.docx](https://github.com/Cadasta/cadasta-project-ideas/files/181823/cadasta.task.1.docx)
i hope you will like it .
thank you.

**Comment by wonderchook** [comment]
@deeptireddy thanks for the submission. You might try to think of questions where people walk through their daily steps rather than asking them what they do every day. Something like "what is your main task?" and then "can you walk me through the task as if I have to do it?"

**Comment by wonderchook** [comment]
@Anagha1 you will want to check your spelling on your submission. For example please spell out "you" instead of "u".

**Comment by SonaliAg** [comment]
@wonderchook can you please look at my submission. [here](https://github.com/SonaliAg/Cadasta/wiki/Land-and-Resource-Rights-Community-Research-and-Segment-Analysis---Initial-Task)

**Comment by MMBazel** [comment]
Hi @wonderchook, wanted to check in with you and see what your thoughts are on the updated interview questions, specifically the technology focused section? [Questions](https://github.com/MMBazel/Cadasta/wiki/Land-and-Resource-Rights-Expert-Interview-(10-Questions))

**Comment by deeptireddy** [comment]
Hello @wonderchook 
Thanks a lot for your valuable feedback. I have applied the changes and made a new set of questions.
Please review the same.
Thank you,

[cadasta.docx](https://github.com/Cadasta/cadasta-project-ideas/files/182419/cadasta.docx)

**Comment by Anagha1** [comment]
Hi@wonderchook @TheaGlitter 
Thanks for your feedback and suggestions. I have made changes. Please suggest more. 
Thank you
[cadasta.task.1 1.docx](https://github.com/Cadasta/cadasta-project-ideas/files/184055/cadasta.task.1.1.docx)

**Comment by wonderchook** [comment]
thanks all for your updates. I look forward to your applications.

**Comment by MMBazel** [comment]
Hi @wonderchook @TheaGlitter , thanks for taking the time to consider my application and the opportunity to participate. Would it be possible to find out why someone wasn't accepted?

**Comment by wonderchook** [comment]
Hi @MMBazel we ended up not being able to accept anyone for this project.

**Comment by MMBazel** [comment]
@wonderchook I'm sorry to hear that. Is there anyway to still contribute? I really like the work that you guys and it would be good to be able to keep helping out, even in a limited capacity.

**Comment by wonderchook** [comment]
@MMBazel we won't be doing this type of analysis anytime soon. We'll be releasing another version of the Cadasta Platform end of June. We invite anyone to provide feedback on that. You can opt into our newsletter to find out more updates as things progress. http://cadasta.org/newsletter-optin/

We also will be offering internships against in the next December round.
